language: python

python:
  - "3.9"

install:
  - pip install -r requirements-dev.txt
  - pip install -r requirements.txt

script:
  - pytest -v --cov=./
  
after_success:
  - codecov

deploy:
  provider: pypi
  user: __token__
  password: $AUTH_PYPI
  on:
    tags: true
