language: python

python:
  - "3.9"

before_install:
  - pip install --upgrade pip
  - pip install --upgrade pytest
  - pip install --upgrade codecov
  - pip install -r requirements-dev.txt
  - pip install -r requirements.txt

install:
  - pip install .

script:
  - pytest -v --cov=./

after_success:
  - codecov

deploy:
  provider: pypi
  user: __token__
  password: $AUTH_PYPI
  on:
    tags: true
